name: Flutter Security Scan

on:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Build APK
        run: |
          cd Shortzz_flutter/Shortzz
          flutter pub get
          flutter build apk --release
          mkdir -p final_apk
          cp build/app/outputs/flutter-apk/app-release.apk ../../final_apk/

      - name: Start MobSF in Docker
        run: |
          docker pull opensecurity/mobile-security-framework-mobsf
          docker run -d -p 8080:8000 --name mobsf opensecurity/mobile-security-framework-mobsf

      - name: Aguarda MobSF iniciar (delay)
        run: sleep 40

      - name: Verificar se MobSF está no ar
        run: curl http://localhost:8080

      - name: Obter API Key do MobSF
        id: get_key
        run: |
          APIKEY=$(curl -s http://localhost:8080/api/v1/apikey | jq -r '.api_key')
          echo "APIKEY=$APIKEY" >> $GITHUB_ENV

      - name: Upload APK para MobSF
        id: upload_apk
        run: |
          response=$(curl -s -X POST "http://localhost:8080/api/v1/upload" \
            -H "Authorization: $APIKEY" \
            -F "file=@final_apk/app-release.apk")
          echo "$response" > mobsf-response.json
          echo "SCAN_HASH=$(echo "$response" | jq -r '.hash')" >> $GITHUB_ENV

      - name: Baixar relatório PDF
        run: |
          curl -X POST "http://localhost:8080/api/v1/download_pdf" \
            -H "Authorization: $APIKEY" \
            -H "Content-Type: application/json" \
            -d "{\"hash\":\"$SCAN_HASH\"}" \
            -o mobsf-report.pdf

      - name: Baixar relatório JSON
        run: |
          curl -X POST "http://localhost:8080/api/v1/report_json" \
            -H "Authorization: $APIKEY" \
            -H "Content-Type: application/json" \
            -d "{\"hash\":\"$SCAN_HASH\"}" \
            -o mobsf-report.json

      - name: Upload artefatos (APK + relatórios)
        uses: actions/upload-artifact@v4
        with:
          name: mobsf-results
          path: |
            final_apk/app-release.apk
            mobsf-report.pdf
            mobsf-report.json
            mobsf-response.json
