name: Flutter Security Scan

on:
  push:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Build APK
        run: | 
          cd Shortzz_flutter/Shortzz
          flutter build apk --release

      - name: Upload APK to MobSF
        run: |
          curl -X POST "http://localhost:8080/api/v1/upload" \
          -H "Authorization: ${{ secrets.MOBSF_API_KEY }}" \
          -F "file=@build/app/outputs/flutter-apk/app-release.apk"

