name: Flutter Security Scan

on:
  push:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Tentar baixar APK salvo anteriormente
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk
          path: ./build_downloaded

      - name: Verificar se APK foi baixado
        id: apk_check
        run: |
          if [ -f build_downloaded/app-release.apk ]; then
            echo "APK_FOUND=true" >> $GITHUB_OUTPUT
          else
            echo "APK_FOUND=false" >> $GITHUB_OUTPUT
          fi

      - name: Build APK (caso não encontrado)
        if: steps.apk_check.outputs.APK_FOUND == 'false'
        run: |
          cd Shortzz_flutter/Shortzz
          flutter pub get
          flutter build apk --release

      - name: Copiar APK para caminho comum
        run: |
          mkdir -p ./final_apk
          if [ -f build_downloaded/app-release.apk ]; then
            cp build_downloaded/app-release.apk final_apk/
          else
            cp Shortzz_flutter/Shortzz/build/app/outputs/flutter-apk/app-release.apk final_apk/
          fi

      - name: Verificar APK gerado/copied
        run: ls -lh final_apk/

      - name: Upload para MobSF
        run: |
          response=$(curl -s -X POST "http://localhost:8080/api/v1/upload" \
            -H "Authorization: ${{ secrets.MOBSF_API_KEY }}" \
            -F "file=@final_apk/app-release.apk")

          echo "Resposta MobSF: $response"

          echo "$response" > mobsf-response.json

          echo "SCAN_HASH=$(echo "$response" | jq -r '.hash')" >> $GITHUB_ENV

      - name: Baixar relatório PDF
        run: |
          curl -X POST "https://77a8-177-104-203-155.ngrok-free.app " \
            -H "Authorization: ${{ secrets.MOBSF_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{\"hash\":\"$SCAN_HASH\"}" \
            -o mobsf-report.pdf

      - name: Baixar relatório JSON
        run: |
          curl -X POST "http://localhost:8080/api/v1/upload" \
            -H "Authorization: ${{ secrets.MOBSF_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{\"hash\":\"$SCAN_HASH\"}" \
            -o mobsf-report.json

      - name: Upload artefatos (APK + relatórios)
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-result
          path: |
            final_apk/app-release.apk
            mobsf-report.pdf
            mobsf-report.json
            mobsf-response.json
